/**
 * services/appointmentScheduler.js
 * Mise à jour automatique des statuts de rendez-vous + facturation médecin
 *
 * Transitions :
 *  confirmed → ongoing    quand appointmentDate <= maintenant
 *  ongoing   → completed  quand appointmentDate + duration <= maintenant
 *  completed (nouveau)  → DoctorPayment créé automatiquement (paymentMethod='auto')
 *  pending   → missed     si pas confirmé et appointmentDate + 2h <= maintenant
 */

const cron   = require('node-cron');
const { Op } = require('sequelize');

let _models = null;
const getModels = () => {
  if (!_models) _models = require('../models');
  return _models;
};

// ─── 1. confirmed → ongoing ───────────────────────────────────────────────────
async function markOngoing() {
  try {
    const { Appointment } = getModels();
    const [count] = await Appointment.update(
      { status: 'ongoing' },
      { where: { status: 'confirmed', appointmentDate: { [Op.lte]: new Date() } } }
    );
    if (count > 0) console.log(`🔄 [Scheduler] ${count} rendez-vous → "En cours"`);
  } catch (err) {
    console.error('❌ [Scheduler] markOngoing:', err.message);
  }
}

// ─── 2. ongoing → completed + facturation ────────────────────────────────────
async function markCompleted() {
  try {
    const { Appointment, User, DoctorPayment, sequelize } = getModels();
    if (!DoctorPayment) return;

    const now = new Date();

    // Charger tous les rendez-vous "ongoing" avec infos médecin et patient
    const toComplete = await Appointment.findAll({
      where: { status: 'ongoing' },
      include: [
        { model: User, as: 'doctor',  attributes: ['id', 'consultationPrice', 'firstName', 'lastName'] },
        { model: User, as: 'patient', attributes: ['id', 'firstName', 'lastName'] },
      ],
    });

    for (const apt of toComplete) {
      const endTime = new Date(apt.appointmentDate).getTime() + (apt.duration || 30) * 60 * 1000;
      if (now.getTime() < endTime) continue; // pas encore fini

      await sequelize.transaction(async (t) => {
        // a) Marquer terminé
        await apt.update({ status: 'completed' }, { transaction: t });

        // b) Créer la facturation automatique
        if (apt.doctor) {
          const consultPrice = parseFloat(apt.doctor.consultationPrice) || 0;
          const doctorShare  = parseFloat((consultPrice * 0.9).toFixed(2)); // 90%
          const commission   = parseFloat((consultPrice * 0.1).toFixed(2)); // 10% plateforme
          const period       = new Date().toLocaleDateString('fr-FR', { month: 'long', year: 'numeric' });
          const patientName  = apt.patient ? `${apt.patient.firstName} ${apt.patient.lastName}` : 'Patient inconnu';
          const aptDateStr   = new Date(apt.appointmentDate).toLocaleString('fr-FR');

          await DoctorPayment.create({
            doctorId:          apt.doctorId,
            processedBy:       null,           // null = généré automatiquement
            amount:            doctorShare,
            currency:          'XOF',
            paymentMethod:     'auto',
            paymentDetails: {
              autoGenerated:     true,
              consultationPrice: consultPrice,
              commission,
              appointmentId:     apt.id,
              patientId:         apt.patientId,
            },
            period,
            consultationsCount: 1,
            status:            'pending',
            notes: `Facturation automatique — RDV ${aptDateStr} — ${patientName} — Commission plateforme: ${commission} XOF`,
          }, { transaction: t });

          console.log(`💰 [Scheduler] RDV terminé → Dr. ${apt.doctor.firstName} ${apt.doctor.lastName} : ${doctorShare} XOF`);
        }
      });
    }
  } catch (err) {
    console.error('❌ [Scheduler] markCompleted:', err.message);
  }
}

// ─── 3. pending trop vieux → missed ──────────────────────────────────────────
async function markMissed() {
  try {
    const { Appointment } = getModels();
    const twoHoursAgo = new Date(Date.now() - 2 * 60 * 60 * 1000);
    const [count] = await Appointment.update(
      { status: 'missed' },
      { where: { status: 'pending', appointmentDate: { [Op.lte]: twoHoursAgo } } }
    );
    if (count > 0) console.log(`⚠️ [Scheduler] ${count} rendez-vous → "Manqué"`);
  } catch (err) {
    console.error('❌ [Scheduler] markMissed:', err.message);
  }
}

// ─── Démarrage ────────────────────────────────────────────────────────────────
function startScheduler() {
  console.log('🕐 [Scheduler] Démarrage du planificateur de statuts...');

  // Toutes les minutes
  cron.schedule('* * * * *', async () => {
    await markOngoing();
    await markCompleted();
    await markMissed();
  });

  // Vérification immédiate 3s après le boot (laisse le temps à la BDD)
  setTimeout(async () => {
    console.log('🔄 [Scheduler] Vérification initiale au démarrage...');
    await markOngoing();
    await markCompleted();
    await markMissed();
  }, 3000);

  console.log('✅ [Scheduler] Actif — vérification toutes les minutes');
}

module.exports = { startScheduler };
